### ISSUE TITLE
segfault when compiled for aarch64-linux-gnu

### ISSUE THREAD

**Issue by chadouming** [Raptor3um/Raptoreum#102]
### Describe the issue
Compiled the raptoreum daemon un aarch64 on debian 11/alpine 3.15/ubuntu 20.04 in AWS instances. Each time I'm getting a segfault when I try to start the daemon. It seems to be related to the boost libraries so I tried updating boost libraries to 1.74, the same that come with debian 11 distro, yet I'm still getting the same issue. I also have compiled and run succesfully the vertcoin and ravencoin daemon. Here is the relevant trace:

2022-01-09 15:50:07 ERROR: ReadBlockFromDisk: Errors in block header at CBlockDiskPos(nFile=0, nPos=8)
2022-01-09 15:50:07 *** Failed to read block
2022-01-09 15:50:07 Error: Error: A fatal internal error occurred, see debug.log for details
2022-01-09 15:50:07 Posix Signal: Segmentation fault
   0#: (0xAAAAB9657B50) stl_vector.h:112       - std::_Vector_base<unsigned long, std::allocator<unsigned long> >::_Vector_impl_data::_M_copy_data(std::_Vector_base<unsigned long, std::allocator<unsigned long> >::_Vector_impl_data const&)
   1#: (0xAAAAB9657B50) stl_vector.h:123       - std::_Vector_base<unsigned long, std::allocator<unsigned long> >::_Vector_impl_data::_M_swap_data(std::_Vector_base<unsigned long, std::allocator<unsigned long> >::_Vector_impl_data&)
   2#: (0xAAAAB9657B50) stl_vector.h:1818      - std::vector<unsigned long, std::allocator<unsigned long> >::_M_move_assign(std::vector<unsigned long, std::allocator<unsigned long> >&&, std::integral_constant<bool, true>)
   3#: (0xAAAAB9657B50) stl_vector.h:714       - std::vector<unsigned long, std::allocator<unsigned long> >::operator=(std::vector<unsigned long, std::allocator<unsigned long> >&&)
   4#: (0xAAAAB9657B50) stacktraces.cpp:779    - HandlePosixSignal
   5#: (0xFFFF8BFC77D0) <unknown-file>         - ???
   6#: (0xAAAAB94A1A5C) validation.cpp:499     - UpdateMempoolForReorg(DisconnectedBlockTransactions&, bool)
   7#: (0xAAAAB94AADE0) stl_vector.h:335       - std::_Vector_base<CBlockIndex*, std::allocator<CBlockIndex*> >::~_Vector_base()
   8#: (0xAAAAB94AADE0) stl_vector.h:683       - std::vector<CBlockIndex*, std::allocator<CBlockIndex*> >::~vector()
   9#: (0xAAAAB94AADE0) validation.cpp:2670    - ActivateBestChainStep
  10#: (0xAAAAB94AADE0) validation.cpp:2795    - ActivateBestChain(CValidationState&, CChainParams const&, std::shared_ptr<CBlock const>)
  11#: (0xAAAAB91D607C) shared_ptr_base.h:732  - std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count()
  12#: (0xAAAAB91D607C) shared_ptr_base.h:1183 - std::__shared_ptr<CBlock const, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr()
  13#: (0xAAAAB91D607C) shared_ptr.h:121       - std::shared_ptr<CBlock const>::~shared_ptr()
  14#: (0xAAAAB91D607C) validation.h:291       - ThreadImport(std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >)
  15#: (0xAAAAB92037A0) stl_vector.h:680       - std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >::~vector()
  16#: (0xAAAAB92037A0) bind.hpp:259           - void boost::_bi::list1<boost::_bi::value<std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> > > >::operator()<void (*)(std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >), boost::_bi::list0>(boost::_bi::type<void>, void (*&)(std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >), boost::_bi::list0&, int)
  17#: (0xAAAAB92037A0) bind.hpp:1294          - boost::_bi::bind_t<void, void (*)(std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >), boost::_bi::list1<boost::_bi::value<std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> > > > >::operator()()
  18#: (0xAAAAB92037A0) thread.hpp:120         - boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >), boost::_bi::list1<boost::_bi::value<std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> > > > > >::run()
  19#: (0xAAAAB9863128) <unknown-file>         - ???
  20#: (0xFFFF8BF6E628) <unknown-file>         - ???
  21#: (0xFFFF8BDF701C) <unknown-file>         - ???

#### If so, please list the steps to reproduce below:
1. Build dependencies on aarch64
2. Build daemon
3. Unzip the bootstrap and launching the daemon will give an error. 
4. Relaunching with reindex will complain but won't stop nor load correctly.
5. Launching without the bootstrap will incur the segfault described above.

**Comment by Bigpiggy01** [comment]
You may want to go backwards instead to 1.64. That is what the depends are currently set up to build with.

**Comment by chadouming** [comment]
> You may want to go backwards instead to 1.64. That is what the depends are currently set up to build with.

I kinda used that strategy and tried ubuntu 18.04. To my surprise, that worked. I'm guessing it has something to do with GCC-10.
