### ISSUE TITLE
 raptoreum/depends/packages/expat.mk 

### ISSUE THREAD

**Issue by xcoincoder** [Raptor3um/Raptoreum#103]
package=expat
$(package)_version=2.2.1
$(package)_download_path=https://downloads.sourceforge.net/project/expat/expat/$($(package)_version)
$(package)_file_name=$(package)-$($(package)_version).tar.bz2
$(package)_sha256_hash=1868cadae4c82a018e361e2b2091de103cd820aaacb0d6cfa49bd2cd83978885

This is no longer source

Please update

package=expat
$(package)_version=2.2.1
$(package)_download_path=https://github.com/libexpat/libexpat/releases/download/R_2_2_1/
$(package)_file_name=$(package)-$($(package)_version).tar.bz2
$(package)_sha256_hash=1868cadae4c82a018e361e2b2091de103cd820aaacb0d6cfa49bd2cd83978885

**Comment by xcoincoder** [comment]
PACKAGE=qt
$(package)_version=5.7.1
$(package)_download_path=https://download.qt.io/archive/qt/5.7/$($(package)_version)/submodules
$(package)_suffix=opensource-src-$($(package)_version).tar.gz
$(package)_file_name=qtbase-$($(package)_suffix)
$(package)_sha256_hash=95f83e532d23b3ddbde7973f380ecae1bac13230340557276f75f2e37984e410


to new source

https://download.qt.io/new_archive/qt/5.7/5.7.1/submodules/

**Comment by Bigpiggy01** [comment]
This no longer applies following the rebase to Dash17.
