### ISSUE TITLE
Incorrect column types in Smartnodes tab

### ISSUE THREAD

**Issue by dhiachou** [Raptor3um/Raptoreum#104]
### Describe the issue
In  the GUI wallet's "Smartnodes" tabs, some columns seem to have the incorrect type. 
The concerned columns are `PoSe Score`, `Registered`, `Last Paid` and `Collateral Amount`.
These columns should have an integer type but they have a string type.

#### If so, please list the steps to reproduce below:
1. Go to Smartnodes tab
2. Sort on one of the mentioned columns

### Expected behaviour
Rows should be sorted on the selected column based on the numerical value.

### Actual behaviour
Rows are sorted on the selected column in alphanumerical order

### Screenshots.
![image](https://user-images.githubusercontent.com/6137390/149663050-2c47312f-55f3-4f9d-a585-188ff7e36f93.png)

### What version of Raptoreum Core are you using?
Raptoreum Core version v1.2.15.2-g473165aab (64-bit)

**Comment by dhiachou** [comment]
I believe the solution to this, is to create a subclass of `QTableWidgetItem` say `IntegerTableWidgetItem` and override the comparison operator to compare Int values instead of String values. 

In : https://github.com/Raptor3um/raptoreum/blob/master/src/qt/smartnodelist.cpp

```cpp
class IntegerTableWidgetItem : public QTableWidgetItem {
    public:
        bool operator <(const QTableWidgetItem &other) const
        {
            return text().toInt() < other.text().toInt();
        }
};
```

And adapt the lines 219, 224, 225, 226  to use the IntegerTableWidgetItem subclass.

**Comment by Bigpiggy01** [comment]
Yes, spill over from upstream should be fixed on development branch.
