### ISSUE TITLE
v0.16 v0.17 Cleanup - Names/Misc

### ISSUE THREAD

**Issue by CodeIsTheKey** [Raptor3um/raptoreum#106]
Reviewing PRs #88 and #105, I noted the following files that need review/cleanup:

* contrib/init/raptoreumd.openrcconf - dash -> raptoreum
* doc/release-notes/raptoreum - review release notes - do we want these here?
* doc/release-process.md  - dash -> raptoreum, review
*  contrib/gitian-keys - do we want these here?
* src/qt/README.md - dash -> raptoreum
* src/rpc/rpcevo.cpp - Dash/masternode references need to be fixed
* src/rpc/mining.cpp - get/setgenerate removed?
* src/rpc/misc.cpp - review validate/ismine/iswatchonly - is this an issue?  Units in duffs, dash-cli reference
* src/script/ismine.cpp - HaveKeys logic changed - all must have keys now instead of "at least one"?
* src/util.cpp - ">>>>>" merge conflict remnant
* search for `loggibng.h` - rename/remove?
* src/validationinterface.cpp - smartnode reverted to masternode
* src/Makefile.am - BLS_LIBS - lbls-dash?

**Comment by malbit** [comment]
> Reviewing PRs #88 and #105, I noted the following files that need review/cleanup:
> 
> * contrib/init/raptoreumd.openrcconf - dash -> raptoreum
> * doc/release-notes/raptoreum - review release notes - do we want these here?
> * doc/release-process.md  - dash -> raptoreum, review
> * contrib/gitian-keys - do we want these here?
> * src/qt/README.md - dash -> raptoreum
> * src/rpc/rpcevo.cpp - Dash/masternode references need to be fixed
> * src/rpc/mining.cpp - get/setgenerate removed?
> * src/rpc/misc.cpp - review validate/ismine/iswatchonly - is this an issue?  Units in duffs, dash-cli reference
> * src/script/ismine.cpp - HaveKeys logic changed - all must have keys now instead of "at least one"?
> * src/util.cpp - ">>>>>" merge conflict remnant
> * search for `loggibng.h` - rename/remove?
> * src/validationinterface.cpp - smartnode reverted to masternode

all above been resolved :)

> * src/Makefile.am - BLS_LIBS - lbls-dash?

bls_libs -> bls-dash using bls-signatures with relic toolkit for cryptographic primitives. 
it is compiled while rtm is building and adding static library backed with headers and includes. It is originating to Chia-Network BLS-Signatures Implementation reworked by Dash.
I have already looked at that repo to have it adapt to our needs and soon I am going to recode it and make it maybe built-in to the rtm codebase. For now we may use Dash imolementation till we will have ours :)

**Comment by CodeIsTheKey** [comment]
All items resolved except any BLS or Gitian changes we want in the future.
