### ISSUE TITLE
Raptoreum Lacks BLS-Signatures Repository

### ISSUE THREAD

**Issue by Gapcoin1** [Raptor3um/raptoreum#11]
To report critical security issues, email infosec@raptoreum.org and/or see the RAPTOREUM bug bounty program on [Bugcrowd](https://bugcrowd.com/raptoreumdigitalcash) instead of creating Github issues.

### Describe the issue

Raptoreum does not have it's own linked CHIA BLS-Signatures repository to follow Dash evolution of using CHIA-BLS.

Dash uses it's own forked CHIA repository linking the CHIA BLS to DASH.  

For some reason using the 2018 CHIA BLS allows building Raptoreum, but fails when trying to use the cloned CHIA BLS-Signatures repository after sudo make install.  

https://github.com/Chia-Network/bls-signatures

https://github.com/dashpay/bls-signatures/releases

### Can you reliably reproduce the issue?

Yes

#### If so, please list the steps to reproduce below:

Self-Explanatory 

Raptoreum should have it's own BLS-Signatures Cloned Repository with it's hard-coded linking like Dash does!  

It will automate the building process a lot and help any errors that might be missed in the future with Dash implementing the newer BLS-Signatures code that they are helping to contribute to !

**Comment by Bigpiggy01** [comment]
Hi there,
Apologies for the slow reply we are at the moment focused on getting the next update out but would welcome a pull request on the development branch.
