### ISSUE TITLE
v0.16 v0.17 Cleanup - Active SmartNode Updates

### ISSUE THREAD

**Issue by CodeIsTheKey** [Raptor3um/raptoreum#110]
Reviewing PRs #88 and #105, I noted the following files that need review/cleanup:

The following files need updating to restore pr #58

* src/evo/deterministicmns.cpp
  ToJson - removed fields - review
  removed IsMNValid logic (and in .h)
  active at height logic removed
* src/rpc/rpcevo - active at height removed
* src/wallet/wallet.cpp - active at height removed

**Comment by malbit** [comment]
> Reviewing PRs #88 and #105, I noted the following files that need review/cleanup:
> 
> The following files need updating to restore pr #58
> 
> * src/evo/deterministicmns.cpp
>   ToJson - removed fields - review
>   removed IsMNValid logic (and in .h)
>   active at height logic removed
> * src/rpc/rpcevo - active at height removed
> * src/wallet/wallet.cpp - active at height removed

That issue had been resolved so we can close it I think.
Decision is yours

**Comment by CodeIsTheKey** [comment]
I think we're about half way there.  The optional height parameter was removed that fixed a bug with the active check/collateral in the past.  I need to review and re-apply some of those changes.

**Comment by malbit** [comment]
> I think we're about half way there. The optional height parameter was removed that fixed a bug with the active check/collateral in the past. I need to review and re-apply some of those changes.

Fair enough for me then.
But I did re-add code which was removed by mistake during rebase-merge. 
Will wait for the updates then
