### ISSUE TITLE
Wallet issue

### ISSUE THREAD

**Issue by y0d4a** [Raptor3um/Raptoreum#115]
hi, i got issue with starting wallet:
![image](https://user-images.githubusercontent.com/3115997/153510763-62d532d1-002b-4ae4-92a5-6e582f82db98.png)
any help?

**Comment by Bigpiggy01** [comment]
Hi there,
That file has somehow ended up corrupt.
1) Shut down the wallet
2) Go to %Appdata%raptoreumcore/ and delete the evodb folder
3) Relaunch the wallet allowing time for it to reconstruct the evodb

If the above does not fix it, please revert back on here or join the Discord for live support.

https://discord.gg/HZf42h97pg
