### ISSUE TITLE
Keeps crashing!

### ISSUE THREAD

**Issue by thecarpetjasp** [Raptor3um/Raptoreum#130]
I've been mining for ages now and during the sync - my PC shutdown unexpectedly. Now every time I boot my wallet, it keeps giving me a 'Not responding' message after about 1 minute. I've uninstalled and reinstalled with the bootleg files. I've restored the wallet with my backup. Nothing works! So am I supposed to just accept now I've lost my coins all because we have to use this wallet?

**Comment by CodeIsTheKey** [comment]
Sometimes during the Qt startup, it an be unresponsive.  Give it more time to restart and it should come up (or possibly report a problem from the shutdown).  So long as you have your wallet.dat and backups, your coins are safe.

**Comment by thecarpetjasp** [comment]
> Sometimes during the Qt startup, it an be unresponsive. Give it more time to restart and it should come up (or possibly report a problem from the shutdown). So long as you have your wallet.dat and backups, your coins are safe.

Okay, thank you. Sorry if I sound like a Karen. Just feel like I've wasted so much time. Not sure why I keep getting the same issue every time even after a fresh install. I'll try again tomorrow. Thanks again.

**Comment by CodeIsTheKey** [comment]
No worries - the core code during those starting syncs can get very busy and it doesn't like to talk to Qt during that time.  We have some noticeable improvements coming for that.
