### ISSUE TITLE
rpcport does not work correctly when launching

### ISSUE THREAD

**Issue by sullystuff** [Raptor3um/Raptoreum#148]
rpcuser and rpcpassword seem to be functional but rpcport is not. It defaults to port `10229`

To reproduce:

Start raptoreumd with rpcport=xxxx in command line or $HOME/.raptoreumcore/raptoreum.conf file

raptoreum-cli does not attempt to use specified port either and will default to port 10229, but will correctly use login credentials allowing for control of the daemon as normal with r-cli but nothing else (like curl).

**Comment by Bigpiggy01** [comment]
Yes it switches to up a port per testnet instance so 10229 is correct, it's locked to this for the testnet.

**Comment by sullystuff** [comment]
> Yes it switches to up a port per testnet instance so 10229 is correct, it's locked to this for the testnet.

Gotcha, did not know that.
