### ISSUE TITLE
"safe" in listunspent reporting incorrect value with premature futures transaction

### ISSUE THREAD

**Issue by sullystuff** [Raptor3um/Raptoreum#153]
When using listunspent, premature futures transactions can incorrectly report `"safe": true` when other normal parameters are met. This results in failed transactions when using the input with raw transaction(s).

**Comment by npq7721** [comment]
safe is refer to normal unconfirmed transaction that may be in danger of not getting unconfirmed if it is not ever mined. future transaction would be a confirmed safe transaction. to determine whether an output is a future output use "future" flag and to determine whether future is spendable use "futureSpendable" flag. help listunspent current does not show these 2 new flags so will update the help section

**Comment by CodeIsTheKey** [comment]
Immature future transactions should not be marked safe.  I am updating the logic to set safe to false if the tx is not yet spendable.

**Comment by CodeIsTheKey** [comment]
This has been fixed.
