### ISSUE TITLE
chia_bls/v20181101-dd333043936/src/../contrib/catch/catch.hpp:7422:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’

### ISSUE THREAD

**Issue by andreevmipt** [Raptor3um/Raptoreum#156]
1. Build dependencies: cd depends && make -j8
2. Build errors occured

raptoreum/depends/work/build/x86_64-pc-linux-gnu/chia_bls/v20181101-dd333043936/src/../contrib/catch/catch.hpp:7422:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
7422 |     constexpr static std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;

raptoreum/depends/work/build/x86_64-pc-linux-gnu/chia_bls/v20181101-dd333043936/src/../contrib/catch/catch.hpp:7481:45: error: size of array ‘altStackMem’ is not an integral constant-expression
 7481 |     char FatalConditionHandler::altStackMem[sigStackSize] = {}; 

gcc 11.2.1 20211127
glibc-2.34-r10

**Comment by Raptor3um** [comment]
Depending on OS version when this happened, this is most likely resolved, if not feel free to re-open with further details.
