### ISSUE TITLE
Qt Wallet type filter problem on restart

### ISSUE THREAD

**Issue by CodeIsTheKey** [Raptor3um/Raptoreum#185]
This issue is with the current develop branch.

The Type filter dropdown on the Transactions tab are not set correctly after restarting the wallet.

Steps to reproduce:
1. Open Qt wallet.
2. Go to Transactions tab and filter using the Type dropdown (e.g., Sent To or Received With).
3. Close the wallet.
4. Open the wallet and view transactions.
5. The Type dropdown will show "All" but it will still be filtering on the value used.

I do not see this issue with the Date dropdown (e.g., Last Week) or the text filters.

**Comment by Bigpiggy01** [comment]
I can duplicate this with a many input wallet but not with a sub 50k tx wallet.

**Comment by CodeIsTheKey** [comment]
My 7K tx wallet has this problem.  I haven't tried larger wallets.
