### ISSUE TITLE
Blockchain sync stuck at 69.95%

### ISSUE THREAD

**Issue by GuidoBartoli** [Raptor3um/Raptoreum#209]
### Describe the issue
After a clean install of the Raptoreum official wallet, I'm unable to finish blockchain synchronization even starting from bootstrap. The process is stuck at some point and does not complete, even after removing the software and reinstalling it again.

#### If so, please list the steps to reproduce below:
1. Download and install [official wallet](https://github.com/Raptor3um/raptoreum/releases/download/1.3.17.0/raptoreum-ubuntu20-1.3.17.00.tar.gz)
2. Download [bootstrap](https://bootstrap.raptoreum.com/bootstraps_for_v1.3.17.00/bootstrap.tar.xz) and [powcaches](https://bootstrap.raptoreum.com/powcaches/powcache.dat) into data folder
3. Start wallet and wait for sync to finish... 

### Expected behaviour
Blockchain sync should finish in a reasonable time

### Actual behaviour
Sync is stuck since some days at 69.95% (last transaction: Mon Apr 11 00:35:12 2022)

### Screenshots.
![raptoreum](https://user-images.githubusercontent.com/16103676/190860625-593b5c5e-d7b8-4c79-9465-b46d2ad98821.jpg)

### What version of Raptoreum Core are you using?
Raptoreum Core version v1.3.17.00-42174d8 (64-bit)

### Machine specs:
- OS: Linux Mint 21
- CPU: Intel i7-4600U (4) @ 3.300GHz 
- RAM: 8 GB
- Disk size: 1 TB
- Disk type: SSD

### Any extra information that might be useful in the debugging process.
This is the full [debug.log](https://github.com/Raptor3um/raptoreum/files/9591851/debug.log.zip) zipped because of its large size.

**Comment by Raptor3um** [comment]
Try using only powcache:
- Stop wallet and confirm process is stopped, ps aux | grep raptor as an example.
- Remove in .raptoreumcore the files: blocks, chainstate, evodb, llmq, powcache.dat.
- wget https://bootstrap.raptoreum.com/powcaches/powcache.dat (while in .raptoreumcore)
- Start Raptoreumcore.

Typically sync in this way finishes in 1-2 hours.

**Comment by Bigpiggy01** [comment]
Apart from that, Mint is not a supported distro!

**Comment by GuidoBartoli** [comment]
> Try using only powcache:
> 
> * Stop wallet and confirm process is stopped, ps aux | grep raptor as an example.
> * Remove in .raptoreumcore the files: blocks, chainstate, evodb, llmq, powcache.dat.
> * wget https://bootstrap.raptoreum.com/powcaches/powcache.dat (while in .raptoreumcore)
> * Start Raptoreumcore.
> 
> Typically sync in this way finishes in 1-2 hours.

Ok thanks, I did that and I will wait for it finish.

> Apart from that, Mint is not a supported distro!

Why not? Mint is based on Ubuntu, and the [Raptoreum package](https://github.com/Raptor3um/raptoreum/releases/download/1.3.17.0/raptoreum-ubuntu20-1.3.17.00.tar.gz) is for that distro base. However, it is not the first time I install on Mint and it worked fine in the past.

**Comment by Bigpiggy01** [comment]
Because in situations like building it uses a lot of time better employed elsewhere!

**Comment by Raptor3um** [comment]
Given that Mint is for the most part Ubuntu it may work fine, but unexpected behavior is possible. Another option would be to use something like Gnome Boxes and spin up a Ubuntu 18 or 20 box.

**Comment by GuidoBartoli** [comment]
> Because in situations like building it uses a lot of time better employed elsewhere!

@Bigpiggy01: this may mean that the distribution is less efficient than others, but certainly not that it is not supported.

Anyway, @Raptor3um's solution worked, thanks for the support!

**Comment by michal-zurkowski** [comment]
Getting debug.log could also help in finding what is the problem.
I think there was a problem with Mint before because they do not use standard permissions on their distribution.
Check if /tmp and /var/tmp has proper 1777 permissions. Last time someone came with Mint, that was the problem as those 2 locations do not have write permission by default on Mint.

**Comment by Bigpiggy01** [comment]
Unsupported refers to what the team is willing to spend time and energy on! So yes, it is unsupported!

**Comment by GuidoBartoli** [comment]
> Getting debug.log could also help in finding what is the problem. I think there was a problem with Mint before because they do not use standard permissions on their distribution. Check if /tmp and /var/tmp has proper 1777 permissions. Last time someone came with Mint, that was the problem as those 2 locations do not have write permission by default on Mint.

Yep, they have 1777 permissions, I just checked:
```
guido@SATURN:~$ stat -c '%a' /var/tmp
1777
guido@SATURN:~$ stat -c '%a' /tmp
1777
```
I solved following @Raptor3um suggestion, however in my first question I attached the debug.log if it could be of any help, thanks.

> Unsupported refers to what the team is willing to spend time and energy on! So yes, it is unsupported!

I just posted a question here to eventually get support from the developers, and they were kind enough to explain and propose solutions, while your sentences are pretty rude and technically non-sense, so please calm down.
