### ISSUE TITLE
Typo About section

### ISSUE THREAD

**Issue by wizz13150** [Raptor3um/Raptoreum#216]
### Describe the issue
Double line in the About section in Raptoreum Core.

### Expected behaviour
1 line

### Actual behaviour
2 lines xD

### Screenshots.
![unknown](https://user-images.githubusercontent.com/22177081/193141765-f1069c9b-88ac-4d31-b465-b35e2b863235.png)

### What version of Raptoreum Core are you using?
1.3.17.01

### Machine specs:
- OS: Windows

**Comment by HumbleDeer** [comment]
Is this happening only on the French locale?
