### ISSUE TITLE
Qt wallet not showing recent transactions after start

### ISSUE THREAD

**Issue by CodeIsTheKey** [Raptor3um/Raptoreum#237]
### Describe the issue
When starting raptoreum-qt, recent transactions may not appear in the UI.  Transactions are present in core (listtransactions shows them in the debug window).

### Can you reliably reproduce the issue?
Yes - both with Windows and Ubuntu 20 builds.

#### If so, please list the steps to reproduce below:
1. Close any wallets.
2. Wait until new transactions have occurred for addresses in the wallet.
3. Start raptoreum-qt
4. The transactions that occurred while the UI was stopped may be missing.

### Expected behaviour
All transactions should be visible in the UI

### Actual behaviour
There is a gap in the transactions in the UI, although `listtransactions` shows them in the debug window.  Older transactions are fine and new ones that occur while the UI is running are fine (have confirmed by watching over 40 transactions come in).

### What version of Raptoreum Core are you using?
1.3.17.1

### Any extra information that might be useful in the debugging process.
Current suspicion is that when syncing during startup, we reduce the refresh rate to prevent hanging and that is causing us to miss the new transactions.

**Comment by HumbleDeer** [comment]
So it's just the GUI not showing it, while the daemon has the info? Since cli shows it

**Comment by CodeIsTheKey** [comment]
Correct - the transactions all look good in the core (using the debug window), it is only missing from the UI.

**Comment by HumbleDeer** [comment]
> Correct - the transactions all look good in the core (using the debug window), it is only missing from the UI.

Cheers, thanks for the detailed report.
