### ISSUE TITLE
"Use available balance" leaves space char in sum

### ISSUE THREAD

**Issue by HumbleDeer** [Raptor3um/Raptoreum#255]
#### If so, please list the steps to reproduce below:
1. create a transaction
2. select "use available balance

### Expected behaviour
One complete sum

### Actual behaviour
space character in sum

### Screenshots.
![image](https://user-images.githubusercontent.com/16231288/205454017-39af6971-9881-4a6f-b346-a4b7d73d28a7.png)

### What version of Raptoreum Core are you using?
1.3.17.01

**Comment by rocketsvm** [comment]
https://en.wikipedia.org/wiki/Decimal_separator#Digit_grouping

This is intended behavior in Bitcoin QT since 2014 https://github.com/bitcoin/bitcoin/commit/7007402956579ace12d45cdcfae908802d3d6b6d
