### ISSUE TITLE
Trouble with raptoreum Core wallet

### ISSUE THREAD

**Issue by ForeCross** [Raptor3um/Raptoreum#257]
when i update the wallet, in this moment just stop in this % i put in the ScreenShot

![Raptoreum wallet](https://user-images.githubusercontent.com/95201986/208276119-b84e4d00-a138-4af8-90ec-b701620addba.jpg)

and i try to reescan or update again, but nothing works, just stay in 96.36% in the day 30/11/2022, some one can help with this trouble?, any one know about this issue?, stay tuned!.

**Comment by Blueskys379** [comment]
Yes you need bootstrap the wallet. Follow this procedure,

**How to bootstrap**

Download: <https://bootstrap.raptoreum.com> 
***Use bootstrap version that matches your wallet version***
- Stop wallet or daemon
- In your wallets data directory delete folders:
-- blocks
-- chainstate
-- evodb
-- llmq
- Unpack bootstrap and copy folder into your data directory
- Start wallet
**Data Directory Locations:**
- Unix/Linux: $HOME/.raptoreumcore
- Windows: %AppData%/raptoreumcore

**Comment by Bigpiggy01** [comment]
You also need to delete the powcache and add the powcache from the bootstrap.

**Comment by ForeCross** [comment]
> Yes you need bootstrap the wallet. Follow this procedure,
> 
> **How to bootstrap**
> 
> Download: https://bootstrap.raptoreum.com _**Use bootstrap version that matches your wallet version**_
> 
> * Stop wallet or daemon
> * In your wallets data directory delete folders:
>   -- blocks
>   -- chainstate
>   -- evodb
>   -- llmq
> * Unpack bootstrap and copy folder into your data directory
> * Start wallet
>   **Data Directory Locations:**
> * Unix/Linux: $HOME/.raptoreumcore
> * Windows: %AppData%/raptoreumcore

i do that, but doesn't work :( and i see the pairs is going up numbers (the first number appear in the SS)
![Raptoreum wallet](https://user-images.githubusercontent.com/95201986/208278573-7586592a-d4c6-4866-946b-934543ff6519.jpg)

i try again tomorrow =(

**Comment by ForeCross** [comment]
> You also need to delete the powcache and add the powcache from the bootstrap.

i did that, but doesn't works :(.

**Comment by Blueskys379** [comment]
Double check you are using the right bootstrap.
![image](https://user-images.githubusercontent.com/79267814/208279855-fd96ff80-1291-4ea9-a2a2-c94b5078f84e.jpeg)

Close wallet, delete those four folders and powcache.dat file, copy in 4 folders and powcache.dat from bootstrap and relaunch wallet.

**Comment by taojun0777** [comment]
我也是出现这个问题，弄了好久也没成功，谁能帮帮我呀？

**Comment by Bigpiggy01** [comment]
https://bootstrap.raptoreum.com/

![image](https://user-images.githubusercontent.com/50628656/208511014-19c07f3e-1912-4047-84ff-fdc173c9b5e3.png)

Stop wallet or daemon
In your wallets data directory delete folders:
-- blocks
-- chainstate
-- evodb
-- llmq
** and powcache.dat
Unpack bootstrap and copy folders and powcache.dat into your data directory
Start wallet
Data Directory Locations:
Unix/Linux: $HOME/.raptoreumcore
Windows: %AppData%/raptoreumcore

**Comment by taojun0777** [comment]
> https://bootstrap.raptoreum.com/
> 
> ![图片](https://user-images.githubusercontent.com/50628656/208511014-19c07f3e-1912-4047-84ff-fdc173c9b5e3.png)
> 
> 停止钱包或守护进程 在您的钱包数据目录中删除文件夹： -- blocks -- chainstate -- evodb -- llmq ** 和 powcache.dat 解压引导程序并将文件夹和 powcache.dat 复制到您的数据目录中 启动钱包 数据目录位置： Unix /Linux：$HOME/.raptoreumcore Windows：%AppData%/raptoreumcore

非常感谢

**Comment by taojun0777** [comment]
非常感谢

**Comment by taojun0777** [comment]
能在请教一个事情吗 GPU怎么挖呀

**Comment by Blueskys379** [comment]
Wildrig 矿工直接或在 Raptorhash 矿池上开采其他 gpu 算法并以 RTM 支付。 您可以在 Discord 上获得帮助。

**Comment by ForeCross** [comment]
hice todo eso, pero aun estoy intentando ver si se resuelve, ahora intente cambiar lo del Archivo Configuracion De Raptoreum y reindexo los archivos, aun tarda, asi que espero que resulte, Este es mi Avance:
![Sin título](https://user-images.githubusercontent.com/95201986/208563518-d446dbbc-1faa-4868-921b-e081f78b3e03.jpg)

![Archivo Config](https://user-images.githubusercontent.com/95201986/208563694-91079ea3-dbd6-4b91-94e5-90f07a93f452.jpg)

**Comment by ForeCross** [comment]
![rtm](https://user-images.githubusercontent.com/95201986/208572831-133fe903-cce5-4835-879b-6a9ea6802438.jpg)
Doesn't work =(

**Comment by Blueskys379** [comment]
Under tools menu, click on peers and make sure you are connecting to peers and receiving data.

**Comment by Bigpiggy01** [comment]
Come on the Discord and get Spanish language support closing this issue https://discord.gg/raptoreum

**Comment by maccappuccino** [comment]
Same problem with the raptoreum core with and without wallet.dat, on Windows and same problem on MacOs.



2023-01-13T23:18:59Z ERROR: ConnectBlock(RAPTOREUM): ProcessSpecialTxsInBlock for block c5bc1145370ab9d6f83518ad25a1fbfb3d2f85bf039197a3b7ddccfeca96e9fa failed with bad-cbtx-mnmerkleroot (code 16)
2023-01-13T23:18:59Z InvalidChainFound: invalid block=c5bc1145370ab9d6f83518ad25a1fbfb3d2f85bf039197a3b7ddccfeca96e9fa  height=453101  log2_work=51.97803805  date=2022-11-30T12:14:45Z
2023-01-13T23:18:59Z init message: Starting network threads...
2023-01-13T23:18:59Z InvalidChainFound:  current best=ef41e11e66e9e2de57252276c0501dce413dd0059bc44929fa5a23a4f5c817e4  height=453100  log2_work=51.97803573  date=2022-11-30T12:12:37Z
2023-01-13T23:18:59Z ERROR: ConnectTip(): ConnectBlock c5bc1145370ab9d6f83518ad25a1fbfb3d2f85bf039197a3b7ddccfeca96e9fa failed with bad-cbtx-mnmerkleroot (code 16)
2023-01-13T23:18:59Z InvalidChainFound: invalid block=9a37d07bfec72fa34426f70044e3e0431da2f9fa2263416c5e101c6d601273f7  height=453132  log2_work=51.97810363  date=2022-11-30T13:18:06Z
2023-01-13T23:18:59Z InvalidChainFound:  current best=ef41e11e66e9e2de57252276c0501dce413dd0059bc44929fa5a23a4f5c817e4  height=453100  log2_work=51.97803573  date=2022-11-30T12:12:37Z

**Comment by ForeCross** [comment]
i solved with the new version of raptoreum, download the lastest version https://github.com/Raptor3um/raptoreum/releases and the problem solved easly, good night.

**Comment by maccappuccino** [comment]
Hello,

I didn't dare to use it because of that:
"This will work on mainnet however it is not recommended till it passes further validation."
I'll try it right away and give you a feedback in the ticket

best regards

**Comment by Blueskys379** [comment]
It would start after block 453100 if bootstrap applied. Double check the path of your data directory for the Raptoreumcore folder it is using. In the wallet under information it will show you the path.

**Comment by maccappuccino** [comment]
Thank you ForeCross, it's fixed, it worked fine!
