### ISSUE TITLE
Trouble with raptoreum Core wallet version v1.3.17.01-c136d2b (64-bit)

### ISSUE THREAD

**Issue by maccappuccino** [Raptor3um/Raptoreum#260]
### Describe the issue
Impossible to finish synchro

After 3 months without use, I restart the raptoreum core software on the windows PC because I have mined a little on it. The synchro is impossible, I try all the repairs without success. I decide to upgrade to version v1.3.17.01, it's ko, I start again with the bootstrap, after half a day I'm OK, but no luck I suffer a power cut and there no way to resume the sync.
I decide to start from scratch with an empty wallet, same punishment always blocked between 90-95%.
I change machine, I go on mac with an empty wallet and still the same problem no way to synchronize the raptoreum core with the blockchain.

### Actual behaviour
After 3 weeks without being able to make the blockchain work I decide to contact you, it's the worst chrypto-currency experience I've ever had because I've always been able to fix the others, even the Ethereum wallet which are known to be quite a pain in the ass.

### Screenshots.
![image](https://user-images.githubusercontent.com/65686146/212441507-703b37e5-15e7-44d8-a72e-ffce8177413c.png)

### What version of Raptoreum Core are you using?
v1.3.17.01-c136d2b (64-bit)

### Machine specs:
Windows machine
- OS: Windows 10 
- CPU: 2 x Xeon E5-2630v3 2.40 Ghz (2 x8 cores => 32 Threads)
- RAM: 96 Go DDR4 ECC
- Disk size: 1TB (789 GB free)
- Disk Type (HD/SDD): SSD

MacOs machine
- OS: BigSur 11.6.8
- CPU: Core i5 
- RAM: 32 Go DDR4
- Disk size: 4TB (3,3TB free)
- Disk Type (HD/SDD): SSD

**Comment by maccappuccino** [comment]
I have alway this error (in big log debug.log):

2023-01-13T23:18:59Z ERROR: ConnectBlock(RAPTOREUM): ProcessSpecialTxsInBlock for block c5bc1145370ab9d6f83518ad25a1fbfb3d2f85bf039197a3b7ddccfeca96e9fa failed with bad-cbtx-mnmerkleroot (code 16)
2023-01-13T23:18:59Z InvalidChainFound: invalid block=c5bc1145370ab9d6f83518ad25a1fbfb3d2f85bf039197a3b7ddccfeca96e9fa  height=453101  log2_work=51.97803805  date=2022-11-30T12:14:45Z
2023-01-13T23:18:59Z init message: Starting network threads...
2023-01-13T23:18:59Z InvalidChainFound:  current best=ef41e11e66e9e2de57252276c0501dce413dd0059bc44929fa5a23a4f5c817e4  height=453100  log2_work=51.97803573  date=2022-11-30T12:12:37Z
2023-01-13T23:18:59Z ERROR: ConnectTip(): ConnectBlock c5bc1145370ab9d6f83518ad25a1fbfb3d2f85bf039197a3b7ddccfeca96e9fa failed with bad-cbtx-mnmerkleroot (code 16)
2023-01-13T23:18:59Z InvalidChainFound: invalid block=9a37d07bfec72fa34426f70044e3e0431da2f9fa2263416c5e101c6d601273f7  height=453132  log2_work=51.97810363  date=2022-11-30T13:18:06Z
2023-01-13T23:18:59Z InvalidChainFound:  current best=ef41e11e66e9e2de57252276c0501dce413dd0059bc44929fa5a23a4f5c817e4  height=453100  log2_work=51.97803573  date=2022-11-30T12:12:37Z

**Comment by maccappuccino** [comment]
[debug.log](https://github.com/Raptor3um/raptoreum/files/10416253/debug.log)

**Comment by Blueskys379** [comment]
Hi you need to bootstrap. Your screen shows it's not applied. You need to follow this process. If you need additional support, head to wallet channel on Discord.

**How to bootstrap**

On https://bootstrap.raptoreum.com/  
**Download the version of the bootstrap that matches your current wallet version.**
Use bootstrap version that matches your wallet version
- Stop wallet or daemon
- In your wallets data directory **delete** folders:
-- blocks
-- chainstate
-- evodb
-- llmq
**and the powcache.dat file**
- Unpack bootstrap and copy the four folders and powcache.dat into your data directory
- Start wallet
Data Directory Locations:
- Unix/Linux: $HOME/.raptoreumcore
- Windows: %AppData%/raptoreumcore

**Comment by maccappuccino** [comment]
Thank you, I have already tried this procedure several times without success.

**Comment by Blueskys379** [comment]
Make sure using correct bootstrap version, 1.3.17.00-01 for version 1.3.17.01 Also, use one of the non-indexed versions of the bootstrap and don't change the config file to turn indexing on.

**Comment by maccappuccino** [comment]
That's what I did! 
Now I try again the version 1.13.17.02 testnet and functional in mainnet but not recommended.
ForeCross solved this problem with this new version of raptoreum.
https://github.com/Raptor3um/raptoreum/issues/257

**Comment by maccappuccino** [comment]
Thank you, it's fixed, it worked fine! 
The correction had been made for the previous ticket (https://github.com/Raptor3um/raptoreum/issues/257) but the description of the workaround was missing.

**Comment by Bigpiggy01** [comment]
Glad it got sorted out!
