### ISSUE TITLE
Smartnode Collateral Txes Unlocked After a Full Sync

### ISSUE THREAD

**Issue by CodeIsTheKey** [Raptor3um/Raptoreum#272]
### Describe the issue

When performing a full sync, Smartnode collateral transactions are not locked when the sync completes. The problem is that during initialization, those transactions are locked - but we have not synced the transactions, yet, so they are not locked.

### Can you reliably reproduce the issue?

Yes, any sync that starts before a collateral transaction in our wallet will not lock that transaction.  The easiest way to reproduce is to sync from zero.  If you have a bootstrap from before the collateral transaction was created, that would work also.

### What version of Raptoreum Core are you using?

This was seen in 1.3.17.01 and 1.3.17.02.  I believe it has been an issue before that.

**Comment by nandofw** [comment]
Fixed on pr #271
