### ISSUE TITLE
Raptoreum-qt won't open on macos

### ISSUE THREAD

**Issue by sudormdir** [Raptor3um/Raptoreum#277]
It immediately crashes on launch 

### Machine specs:
- OS: macos 12.4
- CPU: 10 core m1
- RAM: 64 gb
- Disk size: 2tb
- Disk Type (HD/SDD): sdd

**Comment by Bigpiggy01** [comment]
In the data directory delete everything but your wallet.dat powcache.dat and backups folder. Then restart it and let it sync. If you want to speed up the process you can visit https://bootstrap.raptoreum.com and get a bootstrap from there.
