### ISSUE TITLE
fatal error: bls-dash/bls.hpp:

### ISSUE THREAD

**Issue by Zuz99** [Raptor3um/Raptoreum#282]
some file not found 

`Making all in src
make[1]: Entering directory '/home/ari/raptoreum-1.3.17.02/src'
make[2]: Entering directory '/home/ari/raptoreum-1.3.17.02/src'
  CXX      raptoreumd-raptoreumd.o
  CXX      libraptoreum_server_a-addrdb.o
  CXX      libraptoreum_server_a-addrman.o
  CXX      libraptoreum_server_a-batchedlogger.o
  CXX      libraptoreum_server_a-bloom.o
  CXX      libraptoreum_server_a-blockencodings.o
In file included from ./evo/providertx.h:9,
                 from bloom.cpp:9:
./bls/bls.h:17:10: fatal error: bls-dash/bls.hpp: No such file or directory
   17 | #include <bls-dash/bls.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:8146: recipe for target 'libraptoreum_server_a-bloom.o' failed
make[2]: *** [libraptoreum_server_a-bloom.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from ./txmempool.h:27,
                 from blockencodings.cpp:12:
./bls/bls.h:17:10: fatal error: bls-dash/bls.hpp: No such file or directory
   17 | #include <bls-dash/bls.hpp>
`
This issue tracker is only for technical issues related to Raptoreum Core.

General Raptoreum questions and/or support requests and are best directed to the [Raptoreum Discord](https://discord.com/invite/2T8xG7e).

To report critical security issues, DM the Core or Developer Teams instead of creating Github issues.

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Raptoreum Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: ubuntu18
- CPU: 16x AMD EPYC
- RAM: 64GB
- Disk size: 1TB
- Disk Type (NVME):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by nandofw** [comment]
Did you build the depends folder?

Build instruction for ubuntu
```
sudo apt-get install curl build-essential libtool autotools-dev automake pkg-config python3 bsdmainutils cmake -y
git clone https://github.com/Raptor3um/raptoreum.git
make -C depends -j$(nproc)  HOST=x86_64-pc-linux-gnu
./autogen.sh
./configure --prefix=`pwd`/depends/x86_64-pc-linux-gnu
make -j$(nproc)
```
