### ISSUE TITLE
Missing documentation on node mining / solo pool mining.

### ISSUE THREAD

**Issue by nmateo** [Raptor3um/Raptoreum#284]
### Describe the issue
There is no documentation on how to mine directly on the node or create your own pool to mine solo to it.

### Expected behaviour
Documentation on how to entirely solo-mine.

### Actual behaviour
No documentation whatsoever.

### What version of Raptoreum Core are you using?
1.3.17.02

**Comment by michal-zurkowski** [comment]
1. If you want to solo mine with a wallet, it is literally the same as any BTC based wallet. You will have to find miner that has/was modified and works with gbt or getjob mining with smartnodes and other transactions in Coinbase. None that I know of does. Either do not support gbt/getjob or have an outdated codebase.
2. If you want a pool for personal usage, did you check any major modern open-source implementations of pools? I'm pretty sure their setup and tutorials are quite easy to follow and many support RTM/GhostRider algorithm.
MiningCore, YIMMP, YAAMP, and EeasyNomp, all of those should work with minor or no modifications. At most you might have to search for some specific fork that supports GR. I think miningcore in their main repo has already full support for RTM/GR so you might want to check them out.
https://github.com/oliverw/miningcore

**Comment by nmateo** [comment]
Thanks, exactly what i needed !
