### ISSUE TITLE
Not showing transactions from watch-only wallet to spendable wallet.

### ISSUE THREAD

**Issue by michal-zurkowski** [Raptor3um/Raptoreum#29]
### Describe the issue
There seems to be a problem with how the Transaction list is displayed.
Currently, I have my own wallet and recently added an address from another wallet as Watch-Only. I get all transactions in and out from the watch-only address with one exception. When there is a transaction FROM the watch-only wallet TO any wallet that I have access to in my wallet (like the one I use to mine with) it is skipped and is not displayed. It shows neither as a transaction FROM watch only to address X (so -xyz ERM balance), nor as transaction that address X received anything from watch-only address (+xyz RTM to the wallet).
Those transactions 100% exist and are properly there when I check the explorer. Here is one of them from explorer https://explorer.raptoreum.com/tx/d6e97651e8133e56530ed15b53a53dec81db34431e9574da56170f48f1538c11 and a screenshot below from what I can see in the wallet. Screenshot from wallet is missing `RQKcAZBtsSacMUiGNnbk3h3KJAN94tstvt` and `RS48umkD6JmV2GPYmQSX5dUZShNcQW4HCP`
I have to say it looks very similar to how it looks when I send RTM from all my wallets to myself when I compress payouts and only see mini transaction fee I paid in the transaction list, not -X from a wallet or +X to another wallet.

#### If so, please list the steps to reproduce below:
1. Have one wallet X with your address
2. Have wallet Y with another address
3. Add address from wallet Y to wallet X as Watch-only
4. Send some RTM from Y (from address added in step 3) to address on wallet X
5. It should not show up in Wallet X

### Expected behavior
I think both transactions should be present in the Transaction tab. One that goes out of the Watch-Only wallet to wallet X in the wallet as well as that Wallet X received money (or at least this one if both are not possible).

### Actual behavior
The transaction is not present at all.

### Screenshots.
![image](https://user-images.githubusercontent.com/5807270/136986475-31ea3ae3-c914-4e4f-b58b-312200c3fb02.png)

### What version of Raptoreum Core are you using?
ubuntu 18 packages from official releases, version 1.2.15.2

**Comment by npq7721** [comment]
fixed in develop
