### ISSUE TITLE
Error: Expression: oldDMN != nullptr since a few days suddenly.

### ISSUE THREAD

**Issue by enricolanger** [Raptor3um/Raptoreum#322]
This issue tracker is only for technical issues related to Raptoreum Core.

General Raptoreum questions and/or support requests and are best directed to the [Raptoreum Discord](https://discord.com/invite/2T8xG7e).

To report critical security issues, DM the Core or Developer Teams instead of creating Github issues.

#### If so, please list the steps to reproduce below:

a few days ago this error suddenly appeared after trying to start the Raptoreum Core App. System was not changed since. All Windows-Updates done.
I deinstalled Core App 1.3.17.2 - and reinstalled same version - same error
After that I installed newer version 1.3.17.5 - same error
After that I installed newest beta 1.4.17.99 form here - same error
I deinstalled all Visual C++ components from Windows an reinstalled the latest VC++ All-in-One package - same error

### Expected behaviour
App should start and load the database

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version o
![error_after_install](https://github.com/Raptor3um/raptoreum/assets/144841690/4e7d07ef-06db-4029-a3c2-7f892403a631)
![error_after_install](https://github.com/Raptor3um/raptoreum/assets/144841690/194ca47a-9106-4131-ac70-35330640abfa)
f Raptoreum Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
1.3.17.2
1.3.17.5
1.4.17.99 beta

### Machine specs:
- OS: Win 11 22H2 build 22621.2134
- CPU: Ryzen 7 5825U with Radeon Graphics
- RAM: 32GB DDR4-3200 Kingston SK-Hynix
- Disk size: 2TB Kingston SKC3000D2048G
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Blueskys379** [comment]
For running on mainnet you will want to run, 1.3.17.5 and the beta version 1.4.17.99 if want to run the new assets code on testnet. To fix the issue you will need to apply the bootstrap. The bootstrap can be found here https://bootstrap.raptoreum.com

There is a video guide on how to bootstrap here: https://youtu.be/m41ue-xjpMU

Bootstrap doc is here: https://docs.raptoreum.com/raptoreum-docs/raptoreumcore-other/bootstrap/

**Comment by Bigpiggy01** [comment]
Closed,
The fix for mainnet is as @Blueskys379  pointed out to use the correct wallet for mainnet and bootstrap it.
