### ISSUE TITLE
Raptorium mining rewards are too low.

### ISSUE THREAD

**Issue by kbuwel** [Raptor3um/Raptoreum#330]
I don't know where to go to communicate about this topic.
Raptorium is my only income.
For some reason I don't have a job right now.
Mining in a jugpool pool.
Daily earnings fluctuate between 1200rtm on 5900x and 5600x systems.
It costs about 1,200 won in Korean money.
I don’t think I can pay my electricity bill in Korea.
I'm using a node, but the rewards are too low.
I deposited about 10000rtm and received 4rtm or 0.08rtm per day as compensation.
Ultimately, in Korea, this is money that cannot be spent even on paying the electricity bill or 
drinking a glass of water.
If there is a way to increase the reward, please let me know.
I desperately want that method.

**Comment by Balin0x** [comment]
You can use https://raptorhash.net, you will get more coin.
