### ISSUE TITLE
Assertion failed! Expression: oldDmn != nullptr

### ISSUE THREAD

**Issue by GrahamboJangles** [Raptor3um/Raptoreum#332]
### Describe the issue

![image](https://github.com/Raptor3um/raptoreum/assets/36944031/d5fc388b-099c-4000-8bdd-d79aba53a183)

#### If so, please list the steps to reproduce below:
1. Open raptoreum-qt.exe

### What version of Raptoreum Core are you using?
Downloaded raptoreum-win-1.3.17.04 from releases, both the zip file and I tried the installation .exe file.

### Machine specs:
- OS: Windows 10

### Any extra information that might be useful in the debugging process.
I updated all of my Visual C Runtimes

**Comment by Blueskys379** [comment]
Make sure have a backup of wallet.dat file first. Make sure have wallet version 1.3.17.05 and apply the bootstrap and instructions found here, https://docs.raptoreum.com/raptoreum-docs/raptoreumcore-other/bootstrap/
If need addition support, I recommend the Discord support channel.

**Comment by michal-zurkowski** [comment]
You will get it if you open version 1.3.17.02+ but you already opened and have old data from before that version. From 1.3.17.02 some databases and other things were changed and the whole chain has to be redownloaded or rebootstrapped if you do not want to wait (like suggested by Blueskys379)

**Comment by GrahamboJangles** [comment]
I fixed it by deleting the old RaptoreumCore folder. I thought using the installer executable would redirect the software to use the folder pointed during installation, but you have to delete the old one if relocating.

**Comment by michal-zurkowski** [comment]
I think you are confusing the binary installation folder (what you chose while using the installer) (most probably in Program Files) with the folder that stores chain data (by default in %appdata%/raptoreumcore). The chain data folder is chosen once during the first-ever start of the wallet.
