### ISSUE TITLE
Remove custom change address from CoinJoin tab

### ISSUE THREAD

**Issue by Raptor3um** [Raptor3um/Raptoreum#333]
CoinJoin spends inputs completely, any leftover is added to fee to ensure all is spent, because of this there is a check / stop in place to prevent accidentally sending with a overly large fee.

The "Custom Change Address" field and select box should be removed from the CoinJoin tab. 

This is present on both current mainnet release and current testnet release.

![remove change address option](https://github.com/Raptor3um/raptoreum/assets/47279850/1c8f4352-be1b-4acc-92b7-910c96ad1d28)

**Comment by Bigpiggy01** [comment]
Looks to me like the Coinjoin tab isn't displayed at all somehow it's showing a clone of the send tab.

**Comment by nandofw** [comment]
> Looks to me like the Coinjoin tab isn't displayed at all somehow it's showing a clone of the send tab.

send and coinjoin tabs use the same form/code the only difference is on the initialization of the 2 instances (_fCoinJoin = false or true)

`SendCoinsDialog::SendCoinsDialog(bool _fCoinJoin, QWidget *parent) :`

note: the Custom Change Address cannot be removed but it can be hidden (need to see if it don't break the page layout)

**Comment by bertux** [comment]
With the help.of @Bigpiggy01 we will try to explain how to build a fix for this during our first Build in Public screen casting session which will be shared on YouTube.

**Comment by nandofw** [comment]
Fixed on pr #340
