### ISSUE TITLE
Fix network totals display (QT | Testnet)

### ISSUE THREAD

**Issue by Raptor3um** [Raptor3um/Raptoreum#336]
Testnet build version: Latest from actions
OS: Win 11

Currently in QT > Window > Network Traffic: Network totals display is broken.
![testnet-network totals](https://github.com/Raptor3um/raptoreum/assets/47279850/f6641694-30d2-4926-b3b0-b285f4fcedb4)

How it looks on mainnet:
![mainnet-network totals](https://github.com/Raptor3um/raptoreum/assets/47279850/56802600-ff29-4f98-af88-747ee05039a9)

**Comment by nandofw** [comment]
fixed on pr #339
