### ISSUE TITLE
protx list does not handle collateral changes

### ISSUE THREAD

**Issue by CodeIsTheKey** [Raptor3um/Raptoreum#34]
### Describe the issue
When requesting the list of valid protx at a specific height, it assumes the current block height to determine required collateral

### Can you reliably reproduce the issue?
Yes

#### If so, please list the steps to reproduce below:

From the cli, issue the command: `protx list valid false 100000`

### Expected behaviour
I would expect a list of all protx's that had 600K collateral (or a higher level) at that time.

### Actual behaviour
I receive a list of 4 protxs and they all had collateral of 1,000,000 or 1,250,000.

### Screenshots.
![image](https://user-images.githubusercontent.com/88252561/138978223-a7f2415e-9298-453b-86ec-0449abe6628b.png)

### What version of Raptoreum Core are you using?
Raptoreum Core:1.2.15.2

**Comment by npq7721** [comment]
fixed in develop
