### ISSUE TITLE
 Error: -daemon is not supported on this operating system

### ISSUE THREAD

**Issue by RhoyennLabs** [Raptor3um/Raptoreum#362]
### Describe the issue
 Error: -daemon is not supported on this operating system
### Can you reliably reproduce the issue?
yes
#### If so, please list the steps to reproduce below:
1. i follow every single step on https://docs.raptoreum.com/raptoreum-docs/raptoreumcore-cli/installing-and-using-raptoreumcore-cli/ in windows OS (10,11) and 
2.it shows up Error: -daemon is not supported on this operating system

### Expected behaviour
i should be able to use rtm daemon

### Actual behaviour
it doesn't work

**Comment by nandofw** [comment]
As far as i know windows does not support daemonization, more info on [bitcoin pr 8813](https://github.com/bitcoin/bitcoin/pull/8813)
note: you should be able to run the raptoreumd without daemon=1

**Comment by RhoyennLabs** [comment]
perfect!!!! it worked!!! nando you are great indeed sorry if i said that developers were shit. you are not. maybe tri is but you are not indeed.
