### ISSUE TITLE
Future Amount incorrect in transaction data in QT (testnet)

### ISSUE THREAD

**Issue by Raptor3um** [Raptor3um/Raptoreum#38]
### Reproduce

- Receive a future transaction
- Navigate to Transactions
- Double click transaction
- Check "Future Amount"
- 
![future_transaction_amount_mismatch](https://user-images.githubusercontent.com/47279850/140764946-0dc09927-54e0-41bc-97d2-e674f23557fd.png)

**Comment by CodeIsTheKey** [comment]
This will be fixed with PR #73

**Comment by npq7721** [comment]
fixed in develop
