### ISSUE TITLE
Unable To Open Backup Wallet

### ISSUE THREAD

**Issue by Itsmtf** [Raptor3um/raptoreum#4]
Hello Sir! I have 759 RTM In My Wallet And Have more than 5 backup wallets. As I Installed New Windows due to some reasons. After Installation When I Tried To Open Backup Wallet It Is Showing Error that this File Is "Payment Request File Cannot Be Read. This Can Be Cause By Invalid File".

**Comment by npq7721** [comment]
how do u open this. please go to discord for question like this?

**Comment by Raptor3um** [comment]
As this is not an issue with the code it is better to help you on either Telegram or Discord. Please join one of those and ask for support.

Discord: https://discord.gg/2T8xG7e
Telegram: https://t.me/raptoreum
