### ISSUE TITLE
 listassets parameter count doesn't seem to work

### ISSUE THREAD

**Issue by sergeor** [Raptor3um/raptoreum#408]
I'm trying to figure out asset management via rpc and have found the following.
I'm referring to listassets but most likely it applies to all asset commands
1) Help for crul command does not exist, in help listassets
2) The count parameter doesn't seem to work, either I put a string or I put an integer. I have not confirmed whether the start parameter works.
3) The command pattern, according to the wallet api outline, should have the parameters in an array in the param key, but it has them in line. 
Like
`curl --user userpass --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "listassets", "verbose": true, "count": "5", "start": 3}' -H 'content-type: text/plain;' http://127.0.0.1:50001/`

**Comment by nandofw** [comment]
I will add documentation on how to use the command. Here is an example of how to use it with curl:
`curl --user userpass --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "listassets", "params": [true, 10, 10] }' -H 'content-type: text/plain;' http://127.0.0.1:50001/`

**Comment by sergeor** [comment]
nice!
