### ISSUE TITLE
macOS wallet fail

### ISSUE THREAD

**Issue by mrdarkside** [Raptor3um/Raptoreum#43]
The wallet fails on Monteray, just splash screen opens for a second then terminal returns "Posix Signal: Bus Error: 10"

I gave it full disk access still fails.

Saved Apple's Problem Report to a [gist](https://gist.github.com/mrdarkside/7fdd70e5b540c1958c22c7b7b1aae4aa) all specs are there

**Comment by Bigpiggy01** [comment]
Are you using the release candidate? 1.2.15.2 Is broken I've just removed it from releases.

The Candidate build here should work in the meanwhile https://github.com/Raptor3um/raptoreum/releases/tag/1.3.5.99

**Comment by Bigpiggy01** [comment]
We appreciate the debug log by the way it confirms the earlier issue!
