### ISSUE TITLE
Wallet Encription

### ISSUE THREAD

**Issue by RJPMachado** [Raptor3um/Raptoreum#44]
### Describe the issue
Encrypted the wallet using only a password, left the phrase empty.

When I try to decrypt the wallet it asks for the phrase, but i didn't define it, the Ok button is deactivated and only turns on if you insert words in the phrase. Tried to insert the password in the phrase, I get incorrect.

### Expected behaviour
There should be to 2 inputs in the decrypt form, phrase and password. Like there was in the form to encrypt

### Actual behaviour
My wallet is blocked

### What version of Raptoreum Core are you using?
Raptoreum Core versão v1.2.15.2-g473165aab (64-bit)

### Machine specs:
- OS: Windows
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

**Comment by Bigpiggy01** [comment]
Unless you have launched the wallet specifically in HD mode, there is only a single encryption password.

Encrypting in regular wallet mode requires the same password to be entered twice or it will not encrypt the wallet.

**Comment by bdelgado1995** [comment]
You may have backup wallets saved on your PC as it saves previous wallets you've used to open the program. I was able to go back to an earlier unencrypted wallet when I had an issue.
