### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by PanicPaintbrush** [Raptor3um/Raptoreum#47]
### Describe the issue
**Error appears on start up (during loading flash screen):**
Microsoft Visual C++ Runtime Library
Assertion Failed!
Program: C:\Program Files\RaptoreumCore\raptoreum-qt.exe
File: evo/evodb.cpp
Line: 71
Expression: hashBestBlock == hashBlockIndex

Abort/Retry/Ignore
Selecting 'Ignore' seems to allow the wallet to start.

#### If so, please list the steps to reproduce below:
1. Start Raptoreum core
2. Wait
3. Error appears

### Expected behaviour
Tell us what should happen.
Raptoreum should start without errors.

### Actual behaviour
Tell us what happens instead
Raptoreum should started with errors.

### Screenshots.
![rap-error](https://user-images.githubusercontent.com/19163887/141666796-91eba433-e88f-4dc0-ab19-255141cb08d3.png)

### What version of Raptoreum Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: Windows 10 21H1 19043.1348
- CPU: 5900X
- RAM: 64GB 3600 C16
- Disk size: 2TB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
Wallet sync has not completed yet.

**Comment by Bigpiggy01** [comment]
Fixed on current testnet build if it is the same corruption error. Temp fix is:

Update your Visual C++ runtime

Download: https://github.com/Raptor3um/raptoreum/releases/download/1.2.15.2/bootstrap.zip
- Stop wallet or daemon
- In your wallets data directory delete folders:
-- blocks
-- chainstate
-- evodb
-- llmq
- Unzip bootstrap and copy folder into your data directory
- Start wallet

**Comment by PanicPaintbrush** [comment]
@Bigpiggy01 The temp fixed seemed to clear things up so I imagine it's the same error. Thanks.
