### ISSUE TITLE
relic/src/md/blake2.h:110:5: error: size of array element is not a multiple of its alignment

### ISSUE THREAD

**Issue by cryptopsy0** [Raptor3um/Raptoreum#48]
Using gcc-11, doing make in the depends directory:
`
In file included from /root/.p/raptoreum/depends/work/build/x86_64-pc-linux-gnu/chia_bls/v20181101-5d864d90f15/contrib/relic/src/md/blake2s-ref.c:18:
/root/.p/raptoreum/depends/work/build/x86_64-pc-linux-gnu/chia_bls/v20181101-5d864d90f15/contrib/relic/src/md/blake2.h:101:5: error: size of array element is not a multiple of its alignment
  101 |     blake2s_state S[8][1];
      |     ^~~~~~~~~~~~~
/root/.p/raptoreum/depends/work/build/x86_64-pc-linux-gnu/chia_bls/v20181101-5d864d90f15/contrib/relic/src/md/blake2.h:102:5: error: size of array element is not a multiple of its alignment
  102 |     blake2s_state R[1];
      |     ^~~~~~~~~~~~~
/root/.p/raptoreum/depends/work/build/x86_64-pc-linux-gnu/chia_bls/v20181101-5d864d90f15/contrib/relic/src/md/blake2.h:109:5: error: size of array element is not a multiple of its alignment
  109 |     blake2b_state S[4][1];
      |     ^~~~~~~~~~~~~
/root/.p/raptoreum/depends/work/build/x86_64-pc-linux-gnu/chia_bls/v20181101-5d864d90f15/contrib/relic/src/md/blake2.h:110:5: error: size of array element is not a multiple of its alignment
  110 |     blake2b_state R[1];
      |     ^~~~~~~~~~~~~
/root/.p/raptoreum/depends/work/build/x86_64-pc-linux-gnu/chia_bls/v20181101-5d864d90f15/contrib/relic/src/md/blake2s-ref.c: In function ‘blake2s’:
/root/.p/raptoreum/depends/work/build/x86_64-pc-linux-gnu/chia_bls/v20181101-5d864d90f15/contrib/relic/src/md/blake2s-ref.c:329:3: error: size of array element is not a multiple of its alignment
  329 |   blake2s_state S[1];
      |   ^~~~~~~~~~~~~
In file included from /root/.p/raptoreum/depends/work/build/x86_64-pc-linux-gnu/chia_bls/v20181101-5d864d90f15/contrib/relic/src/low/gmp/relic_fp_sqr_low.c:33:
/root/.p/raptoreum/depends/work/build/x86_64-pc-linux-gnu/chia_bls/v20181101-5d864d90f15/contrib/relic/src/low/gmp/relic_fp_sqr_low.c: In function ‘fp_sqrm_low’:
/root/.p/raptoreum/depends/work/build/x86_64-pc-linux-gnu/chia_bls/v20181101-5d864d90f15/contrib/relic/include/relic_fp.h:338:33: warning: ‘fp_rdc_monty_comba’ accessing 272 bytes in a region of size 96 [-Wstringop-overflow=]

`

Expecting a normal build with gcc11 on my ryzen 3950x machine

See: https://githubmemory.com/repo/relic-toolkit/relic/issues/202

**Comment by Bigpiggy01** [comment]
I am currently unable to replicate that error with gcc9.3 or 10.2 with dual e5 2696 v3

Will give it a try with latest gcc tomorrow. Gcc seems like the likely culprit though as gcc 11 post dates the current release. We unlikely to be updating the current release till our futures branch is ready for mainnet.

**Comment by lukedupin** [comment]
I had the same issue with GCC 11 on Arch.

Edit the black2.h file, move the ALIGNME(64) from the beginning to the middle.

changed line 64:
`typedef struct ALIGNME( 64 ) __blake2s_state`
and line 89:
`typedef struct ALIGNME( 64 ) __blake2b_state`

Re-run your make -jX in the depends folder and it should work now.

**Comment by mooleshacat** [comment]
I looked all over for solution, this was only one that worked 👍
