### ISSUE TITLE
Windows 64 Fails to load Bootstrap after installation launch. Can't synchronise wallet.

### ISSUE THREAD

**Issue by RayT69** [Raptor3um/Raptoreum#49]
This issue tracker is only for technical issues related to Raptoreum Core.

I have tried both the EXE and the ZIP file methods to install the wallet. The app loads but takes HOURS to reach a small percentage complete of the synchronisation. It has become non-responsive every time. This is very incomplete software and should still be in test phase, not released to the public.

I have already bought RTM and transferred it to my wallet, but i cannot receive it as i cannot even load my wallet. Can i use something like Guarda to receive my RTM there?

I have changed the location i was installing to back to the default location, but it still does not work.
1. Download Wallet - Windows EXE and Windows ZIP versions.
2. Install EXE to default location  // Extract ZIP, then Install to any location (including default)..  multiple tried
3. Wallet gets stuck at "synching headers" and is frozen over 15 minutes this install attempt.  Wallet never synchronises.

Wallet should obviously synchronise and complete the set up to allow me to use it as planned.

Wallet fails to get headers and synchronise at all. Or, if it does start synchronising, it takes 6 hours or more to reach 5%.. disgusting!

Raptoreum Core version v1.2.15.2-g473165aab (64-bit)

List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

My machine runs multiple crypto wallets, so it is not my machine, it is the faulty software

**Comment by asbermudez** [comment]
Having the same issue here!

**Comment by Bigpiggy01** [comment]
1) Ensure you have port 10226 open and forwarded in both firewall and route

2) Add the below to your raptoreum.conf in the datadirectory 
addnode=209.151.150.72 #dedi node 01
addnode=94.237.79.27 #dedi node02
addnode=95.111.216.12 #dedi node 03
addnode=198.100.149.124 #dedi node 04
addnode=198.100.146.111 #dedi node 05
addnode=5.135.187.46 #dedi node 06
addnode=5.135.179.95 #dedi node 07
addnode=139.59.7.178 #dedi node 08
addnode=167.172.60.177 #dedi node 09
addnode=139.162.119.163 #dedi node 10

3) Relaunch the wallet and wait or 

4) Download: https://github.com/Raptor3um/raptoreum/releases/download/1.2.15.2/bootstrap.zip
- Stop wallet or daemon
- In your wallets data directory delete folders:
-- blocks
-- chainstate
-- evodb
-- llmq
- Unzip bootstrap and copy folder into your data directory
- Start wallet

**Comment by RayT69** [comment]
ok, i have been able to synchronise my wallet as i left my pc running all night.. 

As mentioned above in my original post, I have an RTM address that was assigned to the very first wallet i tried to install. I sent RTM from the exchage to that addressd. I have reinstalled the RTM wallet and now the original address transaction is not displayed. How can i recover that RTM on that wallet by adding that address to my new wallet?

**Comment by RayT69** [comment]
RESOLVED MY ADDRESS issue. found other helpful advice on Reddit.. regarding wallet.dat.. and backups..  all good now i have my funds in my new RTM wallet :)
