### ISSUE TITLE
Add wallet backup location option for automatic backup

### ISSUE THREAD

**Issue by zorgoz** [Raptor3um/Raptoreum#51]
**This is a feature request**

### Describe the issue
Currently, the automatic wallet backup is created in subfolder of the data folder chosen during setup. 

### Expected behaviour
There is a way to back up wallet manually to any location, but one key aspect of any automatic backup is that it is generated in a different physical location as the original data - a separate physical drive at least. There should be an option to specify a different location for the automatic wallet backups.

### Actual behaviour
The automatic wallet backup is created in subfolder of the data folder chosen during setup, and there is no mean to change this behaviour.

### What version of Raptoreum Core are you using?
Raptoreum Core version v1.2.15.2-g473165aab (64-bit)

**Comment by Bigpiggy01** [comment]
Spreading sensitive files across a system is not desirable behaviour from software. The default data directories require elevated user privileges to access facilitating a certain level of security, Automating going outside that kind of protection is not desirable.

**Comment by zorgoz** [comment]
Sorry, but this is an incorrect interpretation of several concepts like: security, backup, but the meaning of the word "spreading" also.

Having a different, likewise protected location is anything but "spreading". Having it in a single location is anything but secure. You have seamingly never lost valuable data from hard disk failure.

Just for education: https://www.google.com/amp/s/www.msp360.com/resources/blog/following-3-2-1-backup-strategy/

**Comment by Bigpiggy01** [comment]
With the amount of folder traversing nasties loose across the crypto space, what you are suggesting in the name of convenience, is however much you may feel it's not so, a recipe for enabling theft via malware.
Getting a malware infection where privilege elevation may be the deciding factor between theft and no theft we're staying on the side of safer.

**Comment by zorgoz** [comment]
Nope. You are staying on the side of the seemingly safer while denying users the possibility to go even more safer, and having really low expectations about their level of awareness - which might be true, still out of such an application's scope.

Anyway, I got your point and your decision. Maybe you will reevaluate this in the future and recosider.
