### ISSUE TITLE
README for CLI usage

### ISSUE THREAD

**Issue by justinrush** [Raptor3um/Raptoreum#53]
It would be great if there was a readme for the CLI like there is for the QT. Here's an initial stab at that with some deets on docker and kubernetes setup.
[README.md](https://github.com/Raptor3um/raptoreum/files/7566958/README.md)

**Comment by kimevgen** [comment]
> It would be great if there was a readme for the CLI like there is for the QT. Here's an initial stab at that with some deets on docker and kubernetes setup. [README.md](https://github.com/Raptor3um/raptoreum/files/7566958/README.md)

A small edit - in line 19 there should be a folder ~/.raptoreumcore
Please write how to check the balance and transfer rtm. I can't find any information in "raptoreumd / raptoreum-cli -h"

**Comment by justinrush** [comment]
> > It would be great if there was a readme for the CLI like there is for the QT. Here's an initial stab at that with some deets on docker and kubernetes setup. [README.md](https://github.com/Raptor3um/raptoreum/files/7566958/README.md)
> 
> A small edit - in line 19 there should be a folder ~/.raptoreumcore Please write how to check the balance and transfer rtm. I can't find any information in "raptoreumd / raptoreum-cli -h"

The folks on the discord channel opted to take a more complete guide written by someone else - I'll go ahead and close this issue.

**Comment by Bigpiggy01** [comment]
We are adding this to the reworked documentation site and it should be up fairly soon!
