### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by taewoo12** [Raptor3um/Raptoreum#55]
This issue tracker is only for technical issues related to Raptoreum Core.

General Raptoreum questions and/or support requests and are best directed to the [Raptoreum Reddit](https://www.reddit.com/r/raptoreum/).

To report critical security issues, email infosec@raptoreum.org and/or see the RAPTOREUM bug bounty program on [Bugcrowd](https://bugcrowd.com/raptoreumdigitalcash) instead of creating Github issues.

#### If so, please list the steps to reproduce below:
1. just launched the wallet from my desktop
2.it loads up to 1%
3.it shows the error message

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

![Capture](https://user-images.githubusercontent.com/94685671/142612303-5150cdcc-c04c-4143-8e4c-8dc11e20592f.PNG)
### What version of Raptoreum Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
latest and the only one version
### Machine specs:
- OS: Windows 10 x64 21h2
- CPU: Ryzen 5 3600
- RAM: 16gb 3200mhz
- Disk size: 256gb
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.
![Capture](https://user-images.githubusercontent.com/94685671/142612487-5b784d33-d0fe-4ecf-b441-b65bcc7cc9af.PNG)

**Comment by Bigpiggy01** [comment]
This most likely means that something in the evodb or a block has become corrupt and it causing the hang.

In the datadirectory delete everything except the wallet.dat (which you of course have backed up in multiple locations) then do the following:

Download: https://github.com/Raptor3um/raptoreum/releases/download/1.2.15.2/bootstrap.zip
- Stop wallet or daemon
- In your wallets data directory delete folders:
-- blocks
-- chainstate
-- evodb
-- llmq
- Unzip bootstrap and copy folder into your data directory
- Start wallet
