### ISSUE TITLE
Not syncing

### ISSUE THREAD

**Issue by Moldytzu** [Raptor3um/Raptoreum#57]
### Describe the issue
Not syncing, stuck at Syncing headers (see picture)

### Expected behaviour
Actually sync

### Actual behaviour
Stuck

### Screenshots.
![image](https://user-images.githubusercontent.com/40271862/142720420-5d376487-73b6-4d98-9406-50e49d0d6c47.png)
![image](https://user-images.githubusercontent.com/40271862/142720488-ba297c9a-e155-490d-b0d1-76f185aafc06.png)

### What version of Raptoreum Core are you using?
Raptoreum Core version v1.2.15.2-g473165aab (64-bit)

### Machine specs:
- OS: Windows 10 21H1
- CPU: i5-10400
- RAM: 16G
- Disk size: 64 GB remaining
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
[debug.log](https://github.com/Raptor3um/raptoreum/files/7574231/debug.log)

**Comment by MikeR66c** [comment]
You are receiving data... its 13.6% done with the headers... did you wait for it to sync fully? It takes awhile.

**Comment by Bigpiggy01** [comment]
This exactly, there is a fix coming to speed this up. But it is working just slow.
