### ISSUE TITLE
Pool help

### ISSUE THREAD

**Issue by TimyIsCool** [Raptor3um/Raptoreum#63]
### Describe the issue
I cannot install the pool using the guide on the official site, it gives me a 403 error when i use wget

### Machine specs:
- OS: Ubuntu 20.04
- CPU: amd64
- RAM: 4gb
- Disk size: 40
- Disk Type (HD/SDD): ssd

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by authrequest** [comment]
https://discord.gg/pVUM9cDn
CryptoPool Builders Discord. Maybe someone here can help you

**Comment by Bigpiggy01** [comment]
Replace the url with a newer release from the github.

**Comment by TimyIsCool** [comment]
> Replace the url with a newer release from the github.

witch url exactly?

**Comment by Bigpiggy01** [comment]
Wget is only used in two places in there, the one pointing at the pool daemon the documentation is a bit old.

**Comment by TimyIsCool** [comment]
> Wget is only used in two places in there, the one pointing at the pool daemon the documentation is a bit old.

so how exactly would i install the pool?

**Comment by Bigpiggy01** [comment]
Dude that script is meant as an extra which is why it is on the site not github. It is "as it" This is not the venue for support for it.

**Comment by nmateo** [comment]
Yes but their is literally 0 doc on pool operating/software
