### ISSUE TITLE
1.2.15.3 - SHA256

### ISSUE THREAD

**Issue by qwewer0** [Raptor3um/Raptoreum#65]
### Describe the issue
Want to confirm if this is a misunderstanding on my part or is it really an issue.

The `raptoreum_1.2.15.3_windows_64.zip` file gives:
SHA256: 4B076B4274AE6AB5B9A33BABAA08D9F745F2AD9BFEFE160047F811BF4804FB74

The `Sha.256.Checksum.raptoreum_1.2.15.3_windows_64.zip.txt` file has:
(stdin)= f81ae394287b37df7c2129b53365342c801e075e1ae361b27ca3c6dccf86c46d

**Comment by Bigpiggy01** [comment]
I'm getting old both are the same result added regular sha256sum to the txt file. The other one is Openssl 256.
