### ISSUE TITLE
Splash screen, copyright, new issue template - housekeeping cleanup

### ISSUE THREAD

**Issue by CodeIsTheKey** [Raptor3um/Raptoreum#68]
### Minor housekeeping issues to cleanup

1. Resize the splash screen so that none of the text areas overlap (slight spacing improvement, more height for progress text).
1. Check/update copyrights in prep for 2022.
1. github new issue template text is out of date.  Update text and all references to the current ones.

If you notice others, please add to this list (if this issue is still open) - thanks!

**Comment by npq7721** [comment]
1. It fixed in develop and it is being rework on dash 17 merge.
2. been updated in develop

**Comment by CodeIsTheKey** [comment]
1.  The splash screen text issue is related to Windows scaling.  At 100% the text looks fine.  Will check for an easy fix.

**Comment by CodeIsTheKey** [comment]
1. The scaling issue is trivial and not worth trying to fix.  At 100%, it looks good, at 125% the text overlaps, and at 150%, the image size is doubled and the text then fits again.
2. This has already been done in develop.
3. Fixed.
