### ISSUE TITLE
Testnet is not syncing

### ISSUE THREAD

**Issue by riabikov** [Raptor3um/Raptoreum#69]
Testnet is not syncing. Stops at block 85407.

```
2021-11-29 22:15:26 ERROR: AcceptBlockHeader: block 82630e598f2f61501b740f45f5b08d5ef4d03e330d39ee632399d15b80da898b is marked invalid
2021-11-29 22:15:26 ERROR: invalid header received
```

Raptoreum 1.2.15.3

Machine specs:
- Windows 10 x64 / Ubuntu 20.04:
- i5 6600K / vCPU x2:
- 16 GB / 2 GB:
- 512 GB / 40 GB:
- SSD

Linux:
```
{
  "version": 1021503,
  "protocolversion": 70218,
  "walletversion": 61000,
  "balance": 0.00000000,
  "privatesend_balance": 0.00000000,
  "blocks": 85407,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 5.960464477539062e-08,
  "testnet": true,
  "keypoololdest": 1638212051,
  "keypoolsize": 1000,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""
}
```
Windows:

![image](https://user-images.githubusercontent.com/3933944/143950666-02d8cea9-d7e7-4903-a584-baf5b81aa4f7.png)

**Comment by Bigpiggy01** [comment]
There should be a bootstrap available on discord as well as the release that should get you well past the early broken blocks!
