### ISSUE TITLE
AcceptBlock FAILED

### ISSUE THREAD

**Issue by riabikov** [Raptor3um/Raptoreum#70]
I launched a mining pool on the test network, when I find a solution to a block, I get an error. Can you explain what it means and in which direction to look for a solution?

Raptoreum Core v1.3.15.99-g09ff9aaf5

Wallet Error:
```
ERROR: ProcessNewBlock: AcceptBlock FAILED: bad-cb-founder-payment-not-found, Transaction check failed (tx hash 65096016f95a4ebcf97a221c296fb8e5f12acb88fc9ede5b33dbeca6acb6050f)  (code 16)
```
Mining Pool Error:
```
Submitting block 206104 [00003418554941b0bec495dca65f49e16934939058d1bfe8bbd5ab8ffae3329c] 
Block 206104 submission failed with: bad-cb-founder-payment-not-found 
```
The error condition is located here (206 line) - https://github.com/Raptor3um/raptoreum/blob/master/src/consensus/tx_verify.cpp

**Comment by npq7721** [comment]
please go to discord for further assistant. will close this issue as issue is not for pool problem
https://discord.gg/E2dzhmzm
