### ISSUE TITLE
Can't Download bootstrap file

### ISSUE THREAD

**Issue by SanjithVarun** [Raptor3um/Raptoreum#71]
This issue tracker is only for technical issues related to Raptoreum Core.

I can't able to download bootstrap file. After 60% of download it stopped downloading. Error comes as "needs authorization"

**Comment by CodeIsTheKey** [comment]
I just tried downloading it and didn't have any troubles.

**Comment by SanjithVarun** [comment]
> I just tried downloading it and didn't have any troubles.

I will try again. What will be the problem?

**Comment by CodeIsTheKey** [comment]
Normally, that means you don't have permissions to access the file - but this happened during the download.  I think it was an temporary problem, I would just try again.
