### ISSUE TITLE
Application show distorted font rendering and does not display art all in any text fields or grids.

### ISSUE THREAD

**Issue by rniedosmialek** [Raptor3um/Raptoreum#75]
It appears on my system when I launch raptoreum-qt that all input and display elements except images will not render the font properly and in some cases is invisible on the screen until I select the details to highlight them.

My system is a Ubuntu 20 64bit with KDE 5.22.5

The version of raptorem currently in use is the release 1.2.15.3. I have also the same experience with 1.2.15.2

### Machine specs:
- OS: Ubuntu 20
- CPU: 12 x Inteal Core i7-9750H CPU @ 2.60GHz
- RAM: 32 GB Ram
- Disk size: 225 GB
- Disk Type (HD/SDD): NVME

![raptoreum_splash_screen](https://user-images.githubusercontent.com/1743627/144752328-3f5d5a17-ee8d-447b-ae13-a388d08dbd97.png)

![raptoreum_overview_screen](https://user-images.githubusercontent.com/1743627/144752336-8042dfcd-266c-4e23-bf8d-96af7b046f74.png)

![raptoreum_send_screen](https://user-images.githubusercontent.com/1743627/144752344-3e7467de-e799-4508-8219-0ad9cfcc4fab.png)

![raptoreum_receive_screen](https://user-images.githubusercontent.com/1743627/144752345-9cca5143-af12-4fa8-a0ff-0ae22fad6720.png)

![raptoreum_receive_with_selected_table_text_screen](https://user-images.githubusercontent.com/1743627/144752347-e4740360-0005-4d18-bd19-460b65726b95.png)

![raptoreum_transactions_screen](https://user-images.githubusercontent.com/1743627/144752349-5789bc64-73df-4141-a569-7a18cdbd6994.png)

Any help is appreciated.

**Comment by z7737546436** [comment]
My Wallet GUI can't fit in my 55-inch screen. No matter how much I resize or change the resolution of my screen but the Wallet interface is too big I am not able to view all its options and buttons. I have reported this issue on Discord as well as other forums but no luck

I'm using Debian 11 Bullseye 

![image](https://user-images.githubusercontent.com/77194141/145549721-6516368f-083f-4b1a-af3b-5006986df0b2.png)

**Comment by Bigpiggy01** [comment]
KDE is overriding the regular qt settings for some reason, the easiest fix would be to set the wallet to dark mode.

![image](https://user-images.githubusercontent.com/50628656/145680190-ac2fa261-2d54-4967-9a6b-e79f04d9e66b.png)

**Comment by Bigpiggy01** [comment]
> My Wallet GUI can't fit in my 55-inch screen. No matter how much I resize or change the resolution of my screen but the Wallet interface is too big I am not able to view all its options and buttons. I have reported this issue on Discord as well as other forums but no luck
> 
> I'm using Debian 11 Bullseye
> 
> ![image](https://user-images.githubusercontent.com/77194141/145549721-6516368f-083f-4b1a-af3b-5006986df0b2.png)

I'm not able to reproduce this with Debian11 on a 27 inch monitor. What specific graphics are you running?
