### ISSUE TITLE
ConnectBlock (RAPTOREUM): spork is off

### ISSUE THREAD

**Issue by raptoreumonline** [Raptor3um/Raptoreum#84]
Source code 1.2.15.2, on a GNU/Linux Ubuntu 18.04

Hello,
please, I haven't caught a block in the pool in 10 days
and this text appears to me in debug.log

`ConnectBlock (RAPTOREUM): spork is off, skipping transaction locking checks`

is it some mistake ??
it seems weird to me ....
and about 150 users left
because there was no block for 10 days

**Comment by Bigpiggy01** [comment]
The two are unrelated, this relates to Instasend which we do not have enabled.

**Comment by raptoreumonline** [comment]
And how can I allow it ??

**Comment by Bigpiggy01** [comment]
It has nothing to do with your pool not getting blocks, as to the feature, it is centrally controlled and we will not be turning it on.
