### ISSUE TITLE
Problem with WALLET - 

### ISSUE THREAD

**Issue by THYBA** [Raptor3um/Raptoreum#89]
### My wallet stopped at 45% of the synchronization. No way to continue it

During the installation of the wallet. it's been three days

### Actual behaviour
Blocked 45%

### What version of Raptoreum Core are you using?
Last version
### Machine specs:
- OS: Windows 10
- CPU: Core i3 
- RAM: 16G
- Disk size:
- Disk Type (HD/SDD): 250G

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by MikeR66c** [comment]
This sounds like a local networking issue.  Chances are you lost connection during the sync and now you have some bad data that is stuck.  Try closing the wallet, deleting everything in the data folder except wallet.dat and the backups folder, and then restart.  If you want to sync faster, download and extract the bootstrap from the github assets and unzip it into the data folder before restarting.
