### ISSUE TITLE
MX-Linux Raptoreum-Core Self-Compile Fails

### ISSUE THREAD

**Issue by Gapcoin1** [Raptor3um/raptoreum#9]
### Can you reliably reproduce the issue?

Yes, using MX-Linux

#### If so, please list the steps to reproduce below:

1.   https://github.com/Raptor3um/raptoreum/blob/master/doc/build-generic.md

### Expected behaviour
Raptoreum-Core should Compile

### Actual behaviour
Fatal Error Compiling

### Screenshots.
![Screenshot at 2021-05-16 19-50-09](https://user-images.githubusercontent.com/68176698/118403075-44a76680-b65c-11eb-940e-cf4eb72d44e5.png)

Operating System is MX-Linux and Trisquel OS both Debian/Ubuntu based OS

**Comment by npq7721** [comment]
I believe u not following the instruction. to repeat what instruction said

first build depends

$ cd depends
$ make -j4 # Choose a good -j value, depending on the number of CPU cores available
$ cd ..

then 

$ ./autogen.sh
$ ./configure --prefix=`pwd`/depends/<host>
$ make
$ make install # optional

replace "<host>" which the correct platform that was built in depends build earlier. below as possible hosts

i686-pc-linux-gnu for Linux32
x86_64-pc-linux-gnu for Linux64
i686-w64-mingw32 for Win32
x86_64-w64-mingw32 for Win64
x86_64-apple-darwin11 for MacOSX
arm-linux-gnueabihf for Linux ARM 32 bit
aarch64-linux-gnu for Linux ARM 64 bit

if still fail please attach screen shot on depend build result and your full configure commands

**Comment by Gapcoin1** [comment]
Ok, it Compiles using the Depends ,  I don't know why it failed using the Depends folder last week!  I don't want to communicate with Google that much?  Can it Compile without using Depends Folder?

I got it Mining also............

The Error from the Pre-Compiled Ubuntu18 Raptoreum Miner the Instructions from the 

https://docs.raptoreum.com/#/howtomine

this first part shows how to use the benchmark
#on ubuntu:
sudo **./cpuminer_name** -a gr --benchmark #wait 30 seconds or more to get an avg result / thread (use CTRL+C to cancel)
#on windows start a command line with administrator rights and navigate to the folder with your executable files.

**sudo ./cpuminer_name**

I was using ./cpuminer_zen 

ect...... instead of the 

sudo ./cpuminer a -gr 

Using command 

./cpuminer got it mining.  Not sure why it was so easy on a Sunday!  

I will start bumping Raptoreum Again!

Thanks

But it would be awesome to not ever need to use Google Depends Folder to Compile.  

![Screenshot_2021-05-16_19-30-57](https://user-images.githubusercontent.com/68176698/118420963-99c09800-b6af-11eb-9e61-ee0752eb9125.png)

**Comment by Gapcoin1** [comment]
You can close this issue if you want!

I am pretty sure all these different Crypto-Currency different Compiling ways is just some type of IQ test IDK.  Hopefully I don't fall too far behind!

Thanks

**Comment by npq7721** [comment]
depends is how to compile all dependencies since it is somewhat custom and native lib does not support it. as for miner u prob don't have update to date please join discord if u want to discuss further as well as for further similar issue. this is not the platform for such discussion
