### ISSUE TITLE
Raptoreum core client after "done loading" Not Responding

### ISSUE THREAD

**Issue by DylanMS** [Raptor3um/Raptoreum#92]
1.Raptoreum Core client 64 bit. 
2.Tryed reset pc. delete Temp files.
3. Tryed instaling client

Icon in tray on left and right click nothing shown. 

### Machine specs:
- OS: Windows 10 Pro build:21H2
- CPU: AMD Ryzen 9 5900x
- RAM: 16GB
- Disk size: 256GB (90GB-free)
- Disk Type (HD/SDD): SSD WD-Green

**Comment by MikeR66c** [comment]
How long did you wait?  It is possible it is just syncing headers and needs a good deal of time to do that depending on the network connections.

**Comment by DylanMS** [comment]
I tryed serval times open close. After succesfuly opened it show normaly. Everything is synced. i again closed application and again opened stilll same. i need to kill couple of times and it work. i dont know is it error in windows or application.
