### ISSUE TITLE
Hard disk Full doesn't start "bug"

### ISSUE THREAD

**Issue by cosdal** [Raptor3um/Raptoreum#97]
My hdd is full no more space then the wallet is close until here ok.
I create enough space free in my hdd and i start the wallet but doesn't start.
I install one more time again nothing then i use my backup and now is working well.
Is nice if crashing the wallet must exist something fix or what ever.
Thanks

**Comment by Bigpiggy01** [comment]
We are not going to be adding space checks to the qt wallet.

**Comment by cosdal** [comment]
i didn't ask to check the space but i ask to fix if crashing. That's important all the programs they do. Check it.

**Comment by Bigpiggy01** [comment]
A you don't have enough details on this for me to comment on this other than in the very most general terms. B, what you are talking about does require a running space check, we will not be adding that at this stage.
