### ISSUE TITLE
Build error ubuntu 18

### ISSUE THREAD

**Issue by vuicash** [Raptor3um/Raptoreum#98]
Hello,
I'm build error
Please help
Thank you!

compilation terminated.
Makefile:10226: recipe for target 'bls/libraptoreumconsensus_la-bls.lo' failed
make[2]: *** [bls/libraptoreumconsensus_la-bls.lo] Error 1
make[2]: Leaving directory '/home/vui/Documents/GitHub/raptoreum/src'
Makefile:12061: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/vui/Documents/GitHub/raptoreum/src'
Makefile:738: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by Bigpiggy01** [comment]
Have you done a make in the depends directory first? And what GCC version are you using?

**Comment by anonymousess** [comment]
> 

Sorry
I'm not make the depends.
by the way
May I have question
j4 or -j6 or -j8 
What does it mean?

Thank you


####################################
The document like this
####################################
cd depends/
make HOST=x86_64-w64-mingw32 -j4
cd ../
./autogen.sh
./configure --prefix=`pwd`/depends/x86_64-w64-mingw32
####################################


    i686-w64-mingw32 for Win32
    x86_64-w64-mingw32 for Win64
    x86_64-apple-darwin11 for MacOSX
    arm-linux-gnueabihf for Linux ARM 32 bit
    aarch64-linux-gnu for Linux ARM 64 bit

**Comment by CodeIsTheKey** [comment]
The -j option for make indicates the number of jobs to run in parallel.  You can use all the cores of your PC to build that way.

**Comment by Bigpiggy01** [comment]
You need to make the depends first before building, all the documentation should is up to date. You seem to be looking at the wrong document what you want to use is?
```make HOST=x86_64-pc-linux-gnu```

**Comment by 0x00trust** [comment]
Hello

What's SporkAddresses?
In Dash forum, many people ask about this
https://bitcointalk.org/index.php?topic=5134228.0
https://www.dash.org/forum/threads/activating-masternode-via-spork.17598/#post-170468
https://gist.github.com/t4sk/ac6f2d607c96156ca15f577290716fcc

Please help
Thank you

**Comment by Bigpiggy01** [comment]
They are keys for switching chain features on and off.
