### ISSUE TITLE
Build error on Ubuntu 20

### ISSUE THREAD

**Issue by 0x00trust** [Raptor3um/Raptoreum#99]
Hello
I'm build error on Ubuntu 20
Please help

./bls/bls.h:15:10: fatal error: chiabls/bls.hpp: No such file or directory
   15 | #include <chiabls/bls.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:7692: libraptoreum_server_a-bloom.o] Error 1
make[2]: Leaving directory '/home/leo/Desktop/raptoreum/src'
make[1]: *** [Makefile:12579: all-recursive] Error 1
make[1]: Leaving directory '/home/leo/Desktop/raptoreum/src'
make: *** [Makefile:740: all-recursive] Error 1

**Comment by PostGresSQL** [comment]
Download: https://github.com/codablock/bls-signatures/archive/v20181101.zip
git submodule update --init --recursive
mkdir build
cd build
cmake ../
cmake --build . -- -j 6
sudo make install

when unzipped do the following.

cd v20181101
mkdir build
cd build
cmake ../
make --j4
sudo make install

**Comment by Bigpiggy01** [comment]
> Hello I'm build error on Ubuntu 20 Please help
> 
> ./bls/bls.h:15:10: fatal error: chiabls/bls.hpp: No such file or directory 15 | #include <chiabls/bls.hpp> | ^~~~~~~~~~~~~~~~~ compilation terminated. make[2]: *** [Makefile:7692: libraptoreum_server_a-bloom.o] Error 1 make[2]: Leaving directory '/home/leo/Desktop/raptoreum/src' make[1]: *** [Makefile:12579: all-recursive] Error 1 make[1]: Leaving directory '/home/leo/Desktop/raptoreum/src' make: *** [Makefile:740: all-recursive] Error 1

Have you done a make in depends prior to building?
